sudo: required
dist: bionic

# Only build master and release tags
# branches:
#   only:
#     - master
#     - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

# Choose a lightweight base image; we provide our own build tools.
language:
  c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

services:
  - docker

env:
  global:
    - RUN_INTEGRATION_TESTS=1
    - STACK_ARGS=""

  matrix:
    - DOCKER_VERSION="18.03.1~ce~3-0~ubuntu"         GHCVER=7.10
    - DOCKER_VERSION="5:18.09.9~3-0~ubuntu-bionic"   GHCVER=7.10
    - DOCKER_VERSION="5:19.03.6~3-0~ubuntu-bionic"   GHCVER=7.10

    - DOCKER_VERSION="18.03.1~ce~3-0~ubuntu"         GHCVER=8.0
    - DOCKER_VERSION="5:18.09.9~3-0~ubuntu-bionic"   GHCVER=8.0
    - DOCKER_VERSION="5:19.03.6~3-0~ubuntu-bionic"   GHCVER=8.0

    - DOCKER_VERSION="18.03.1~ce~3-0~ubuntu"         GHCVER=8.0.2
    - DOCKER_VERSION="5:18.09.9~3-0~ubuntu-bionic"   GHCVER=8.0.2
    - DOCKER_VERSION="5:19.03.6~3-0~ubuntu-bionic"   GHCVER=8.0.2

    - DOCKER_VERSION="18.03.1~ce~3-0~ubuntu"         GHCVER=8.6.4
    - DOCKER_VERSION="5:18.09.9~3-0~ubuntu-bionic"   GHCVER=8.6.4
    - DOCKER_VERSION="5:19.03.6~3-0~ubuntu-bionic"   GHCVER=8.6.4

    - DOCKER_VERSION="18.03.1~ce~3-0~ubuntu"         GHCVER=8.8.2
    - DOCKER_VERSION="5:18.09.9~3-0~ubuntu-bionic"   GHCVER=8.8.2
    - DOCKER_VERSION="5:19.03.6~3-0~ubuntu-bionic"   GHCVER=8.8.2

addons:
  apt:
    packages:
    - libgmp-dev
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-ce=${DOCKER_VERSION}

# - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=$DOCKER_VERSION

install:
  - mkdir -p "$HOME"/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - export STACK_YAML=stack-$GHCVER.yaml
  # install Stack
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
  - export PATH=$(stack path --local-install-root):$PATH
  - stack --version

script:
  - stack setup
  - stack update
  - stack build
  - stack test

